#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
participation_search:
  path: /participation/search
  controller: App\Controller\ParticipationsController::search
  methods: [GET]
